import access;

--nodeset staff = [str firstname, str familyname, str role, int age] labels = true;
nodeset students = [str firstname, str familyname, int age] labels = true;
--nodeset visitors = [str firstname, str familyname] labels = true;
 
-- should be false
bool boolValue = "strng" == 1;-- true != (6 % (8/(2-0)) > 2);
bool nextBoolValue = (boolValue || true);

int intValue = 10 % 7;
str strValue = "helloworld";

node s = students.get("cr2");
int a = s.age;--.max(3);

--for i from 0 to 9 step 1 {}

--for i from 1 to -4 step -1 {}

--for i from 1 to 10 {}

--for s from students {}

--if (1) {}

--if (2) {bool hasBoobs = true;}
--elseif (3) {}
--elseif (4) {}
--else {}

--if (5) {}
--else {}

--relationset isVisiting = [];

--relation r = isVisiting.get(0);

--clearBuffer();
--pushHeader(students.id, students.firstname, students.age);

--node student = students.get("cr2");
--int newAge = student.age + 1;
--student.age = newAge;

--pushData(student.id, student.firstname, student.age);

--printBuffer();